name: Cypress Tests - modulo05-test-frontend-v2

on:
  push:
    branches:
      - main
    paths:
      - "modulo05-test-frontend-v2/**.js"
      - "modulo05-test-frontend-v2/**.json"
      - "modulo05-test-frontend-v2/**.yml"

jobs:
  modulo05-test-frontend-v2-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm install
        working-directory: ./modulo05-test-frontend-v2

      - name: Run Cypress tests
        run: npm run test:e2e
        working-directory: ./modulo05-test-frontend-v2
